plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
theme: jekyll-theme-tactile
title: Jean Wheatley
description: 3rd November 1945 - 15th September 2019, aged 73.
